### ISSUE TITLE
Support for GHC 8.4.2

### ISSUE THREAD

**Issue by beerendlauwers** [commercialhaskell/intero#552]
Trying to install with `stack build intero`, I get 

```bash
> stack build intero

Error: While constructing the build plan, the following exceptions were
encountered:

In the dependencies for intero-0.1.31:
    ghc-8.4.2 from stack configuration does not match >=7.8 && <=8.4.1  (latest
              matching version is 8.4.1)
    ghc-paths needed, but the stack configuration has no specified version 
              (latest matching version is 0.1.0.9)
needed since intero is a build target.

Some different approaches to resolving this:

  * Consider trying 'stack solver', which uses the cabal-install solver to
    attempt to find some working build configuration. This can be convenient
    when dealing with many complicated constraint errors, but results may be
    unpredictable.

  * Recommended action: try adding the following to your extra-deps
    in /home/beerend/Projects/*******/stack.yaml:

- ghc-8.4.1
- ghc-paths-0.1.0.9
```

Adding `allow-newer: true` for the later GHC version and `ghc-paths-0.1.0.9` to `stack.yaml unregisters a bunch of packages and then fails with an unrelated build error (see https://github.com/commercialhaskell/intero/issues/243). After fixing that, I get the same as https://github.com/commercialhaskell/intero/issues/539:

```bash
 /tmp/stack20171/intero-0.1.31/src/GhciMonad.hs:48:1: error:
        Could not find module ‘GHCi.ObjLink’
        Use -v to see a list of the files searched for.
       |
    48 | import GHCi.ObjLink as ObjLink
       | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by k-bx** [comment]
Interestingly, I'm pretty sure intero worked for me previously on 8.4. I did "cask update" today and now I see a message about intero not working. Not sure if it's just a coincidence.

**Comment by k-bx** [comment]
Yup, adding this to my `Cask` helped:

```
(depends-on "intero" :git "https://github.com/commercialhaskell/intero.git" :ref "c7f9fe4d3990e229f3b7e57e303e2b9dd5a010b4" :files ("elisp/*.el"))
```

(had to wipe the `.cask` because of another bug)

**Comment by brunoczim** [comment]
I would like intero for GHC 8.4.3

**Comment by brunoczim** [comment]
Actually, the patch number on the version should not matter.

**Comment by ntc2** [comment]
@k-bx: I tried adding the
```
(depends-on "intero" :git "https://github.com/commercialhaskell/intero.git" :ref "c7f9fe4d3990e229f3b7e57e303e2b9dd5a010b4" :files ("elisp/*.el"))
```
you suggest but then installing fails. With `cask update` I get the error
```
Wrong type argument: cask-dependency, void-function
```
and with `cask install` I get the error
```
Dependency intero failed to install: Symbol’s function definition is void: package-build-checkout
```
(The `package-build` package is installed.)

Any ideas?

**Comment by k-bx** [comment]
@ntc2 no specific ideas. Please try `cask install --debug` and `cask install --verbose`, I see they're linked in this issue https://github.com/cask/cask/issues/291

Sometimes I have to nuke `.cask` dir to nuke caches and I also sometimes need to launch emacs and do `package-list-packages` to accept all the certificate questions it asks (answering `a` for `Always`)

Unfortunately, Emacs is far from being the friendliest there

**Comment by ntc2** [comment]
@k-bx It's working now, thanks! I updated `cask` to the latest version using `cask upgrade` and deleted `.cask` as you suggested.

One thing that caused me confusion was that after I got past the error message you helped me with, I thought my `cask` setup was still broken because when I did `cask install` the `intero` files would end up in `.cask/25.3/elpa/intero-<date>.<time>` the same as before. Since I was trying to install from GitHub, not from ELPA, I thought this meant it was ignoring my custom `:git` based `depends-on` entry for `intero`. But, it turns out, that's just where the files end up; I still don't understand why ...

**Comment by ntc2** [comment]
@k-bx Forgot to add: just changing the `intero` entry in my `Cask` file was not enough to actually be able to use `intero` in Emacs with GHC 8.4.3, because even the latest `intero.el` makes Emacs use version 0.1.30 of the `intero` Haskell package, which fails to build. In order to use `intero` in Emacs with GHC 8.4.3 I had to also change `(t "0.1.30")` to `(t "0.1.32")` in the `intero.el` file:

https://github.com/commercialhaskell/intero/blob/0ac2d345f26b5fd05d00f84c3b5607800660082a/elisp/intero.el#L77

I'm not sure if @chrisdone just forgot to bump the version number, or if the Haskell code has somehow gotten ahead of the elisp code, and the elisp code is currently incompatible with the latest Haskell. I'm using them together with no problems so far today, but haven't stress tested the combination much yet.

**Comment by k-bx** [comment]
@ntc2 glad it works! I have `'(intero-package-version "0.1.31")` in my `.emacs` in the `custom-set-variables` section, you can probably do the same to not have to edit the intero.el

**Comment by chrisdone** [comment]
Oh, thanks for the reminder. I just need to bump the version in the Elisp.

**Comment by chrisdone** [comment]
Bumped.

**Comment by jgrosso** [comment]
@brunoczim For me, manually installing Intero in my project's directory (i.e. running `stack install intero`) got it working for 8.4.3.

**Comment by renzhi** [comment]
@jgrosso What's your OS and version to make intero work with 8.4.3? I have tried different ways to install intero 0.1.32 with 8.4.3 to no avail, it keeps on complaining about undefined reference to ffi_prep_cif and a bunch of ffi_type_*, despite having the libffi-dev installed. I'm on Debian testing. Intero with 8.2.2 was working fine.

**Comment by jgrosso** [comment]
@renzhi I'm on macos High Sierra, but the compilation never _failed_ per se.... In my case, Stack died earlier when trying to find the right version of `intero` on Stackage. Maybe the FFI problems are different altogether?
Sorry I can't be more help (and hope you get it working)!
