### ISSUE TITLE
Add support for GHC 8.2.2

### ISSUE THREAD

**Issue by bonds** [commercialhaskell/intero#494]
Caption Obvious here. Intero does not yet support the shiny new GHC 8.2.2:

````
~ ❯❯❯ stack build --resolver nightly-2017-11-29 intero                      Wed 2017-11-29 09:56:31 -0800
Downloaded nightly-2017-11-29 build plan.

Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for intero-0.1.23:
    ghc-8.2.2 must match >=7.8 && <8.2.2 (latest applicable is 8.2.1)
needed for unknown reason - stack invariant violated.

Plan construction failed.
````

**Comment by chrisdone** [comment]
I've tested it and it builds, so I'll probably update the test suite and build matrix and cut a new release.

**Comment by vagifverdi** [comment]
Any update on this? It's the only thing that is holding me from moving to 8.2.2

**Comment by msmorgan** [comment]
Stack resolver "lts-10.0" was released today, and uses GHC 8.2.2.

**Comment by chrisdone** [comment]
@msmorgan thanks for the heads up. I've got time to do this so I'll do it now.

**Comment by chrisdone** [comment]
I've uploaded the latest intero to hackage. Hackage is running slow at the moment so you might have to give it an hour or so. It took two attempts to upload the package.

Once an update happens [here](https://github.com/commercialhaskell/all-cabal-hashes/commits/hackage) and [intero on stackage](https://www.stackage.org/package/intero) is 0.1.24, update your elisp.

**Comment by vagifverdi** [comment]
Hmm, I getting following error, while trying to compile intero:

intero-0.1.24: configure
intero-0.1.24: build

--  While building custom Setup.hs for package intero-0.1.24 using:
      /home/vverdi/.stack/setup-exe-cache/x86_64-linux-nopie/Cabal-simple_mPHDZzAJ_2.0.1.0_ghc-8.2.2 --builddir=.stack-work/dist/x86_64-linux-nopie/Cabal-2.0.1.0 build --ghc-options " -ddump-hi -ddump-to-file -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/vverdi/mws-internal/.stack-work/logs/intero-0.1.24.log

    Configuring intero-0.1.24...
    Preprocessing executable 'intero' for intero-0.1.24..
    Building executable 'intero' for intero-0.1.24..
    [1 of 8] Compiling GhciTypes        ( src/GhciTypes.hs, .stack-work/dist/x86_64-linux-nopie/Cabal-2.0.1.0/build/intero/intero-tmp/GhciTypes.o )
    [2 of 8] Compiling GhciMonad        ( src/GhciMonad.hs, .stack-work/dist/x86_64-linux-nopie/Cabal-2.0.1.0/build/intero/intero-tmp/GhciMonad.o )
    [3 of 8] Compiling GhciTags         ( src/GhciTags.hs, .stack-work/dist/x86_64-linux-nopie/Cabal-2.0.1.0/build/intero/intero-tmp/GhciTags.o )
    [4 of 8] Compiling GhciInfo         ( src/GhciInfo.hs, .stack-work/dist/x86_64-linux-nopie/Cabal-2.0.1.0/build/intero/intero-tmp/GhciInfo.o )
    [5 of 8] Compiling GhciFind         ( src/GhciFind.hs, .stack-work/dist/x86_64-linux-nopie/Cabal-2.0.1.0/build/intero/intero-tmp/GhciFind.o )
    [6 of 8] Compiling Paths_intero     ( .stack-work/dist/x86_64-linux-nopie/Cabal-2.0.1.0/build/intero/autogen/Paths_intero.hs, .stack-work/dist/x86_64-linux-nopie/Cabal-2.0.1.0/build/intero/intero-tmp/Paths_intero.o )
    [7 of 8] Compiling InteractiveUI    ( src/InteractiveUI.hs, .stack-work/dist/x86_64-linux-nopie/Cabal-2.0.1.0/build/intero/intero-tmp/InteractiveUI.o )
    [8 of 8] Compiling Main             ( src/Main.hs, .stack-work/dist/x86_64-linux-nopie/Cabal-2.0.1.0/build/intero/intero-tmp/Main.o )
    Linking .stack-work/dist/x86_64-linux-nopie/Cabal-2.0.1.0/build/intero/intero ...
    /home/vverdi/.stack/programs/x86_64-linux/ghc-nopie-8.2.2/lib/ghc-8.2.2/ghc-8.2.2/libHSghc-8.2.2-ghc8.2.2.so: error: undefined reference to 'set_curterm'
    collect2: error: ld returned 1 exit status
    `gcc' failed in phase `Linker'. (Exit code: 1)

------
Btw my own projects compile fine on 8.2.2

**Comment by chrisdone** [comment]
That's defined in the terminfo package: https://github.com/judah/terminfo/blob/d879cf56dbaf9a536a5927ac15caef27dbfb807f/System/Console/Terminfo/Base.hs#L69

Perhaps this doesn't work on Linux on GHC 8.2? I'd say run their test suite, but of course they have no test suite. :roll_eyes: 

I'll try building it on a Linux machine.

**Comment by chrisdone** [comment]
I see `x86_64-linux-nopie` - does that affect things?

**Comment by chrisdone** [comment]
Oh, you can disable terminfo with a flag: https://github.com/judah/haskeline/blob/019e08f2c91b7cc45e5fb98189193a9f5c2d2d57/haskeline.cabal#L37..L40

Try e.g. `stack build intero --flag haskeline:-terminfo`

**Comment by krisajenkins** [comment]
FWIW, I got this error after upgrading the emacs package:

```
    /tmp/stack7518/intero-0.1.24/src/GhciMonad.hs:47:1: error:
        Could not find module ‘GHCi.ObjLink’
        Use -v to see a list of the files searched for.
       |
    47 | import GHCi.ObjLink as ObjLink
       | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Calling `stack install intero-0.1.24 --resolver=lts-10.0` outside of my project directory seems to have fixed it.

Thanks for updating intero so quickly Chris. :-D

**Comment by vagifverdi** [comment]
Thank you Chris! The stack build intero --flag haskeline:-terminfo did build fine and emacs picked it up.
I wonder though what am I missing on my machine that haskeline does not build with terminfo. Perhaps some C lib is not installed.

**Comment by chrisdone** [comment]
@vagifverdi Great, then I'll add that flag to the Emacs mode for when it auto-installs intero.

**Comment by rikvdkleij** [comment]
I wonder why Intero 0.1.24 is still not on Stackage.

**Comment by rikvdkleij** [comment]
I see that the behavior of `stack build` is changed with Stack version 1.6, so to build intero it is not necessary anymore that it has to be on Stackage if compatible version is on Hackage.

**Comment by effectfully** [comment]
I'm getting

```
    /tmp/stack11034/intero-0.1.24/src/GhciMonad.hs:47:1: error:
        Could not find module ‘GHCi.ObjLink’
        Use -v to see a list of the files searched for.
       |
    47 | import GHCi.ObjLink as ObjLink
```

on lts-11.11.

**Comment by beerendlauwers** [comment]
@effectfully I encountered this issue as well. I've managed to work around it with a minimal `stack.yaml` definition (see https://github.com/commercialhaskell/intero/issues/504#issuecomment-355055701) and the `--copy-compiler-tool` flag (see https://github.com/commercialhaskell/intero/pull/505).

In short, this is what I did:

- Make a new simple project with `stack new new-template`
- Go to the project and change the resolver to the one you need Intero for (I needed `resolver: ghc-8.4.2`).
- In the project, do `stack build intero --copy-compiler-tool`, adding `extra-deps` as needed. 

Here's how my output looked like:

```bash
beerend@beerend-ThinkPad-X1-Carbon-5th:~/Projects/intero-builder/new-template$ stack build intero

Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for intero-0.1.32:
    ghc-paths needed, but the stack configuration has no specified version  (latest matching version is 0.1.0.9)
    network needed, but the stack configuration has no specified version  (latest matching version is 2.7.0.2)
    random needed, but the stack configuration has no specified version  (latest matching version is 1.1)
    syb needed, but the stack configuration has no specified version  (latest matching version is 0.7)
needed since intero is a build target.

Some different approaches to resolving this:

  * Consider trying 'stack solver', which uses the cabal-install solver to attempt to find some working build configuration. This can be convenient when dealing with many complicated
    constraint errors, but results may be unpredictable.

  * Recommended action: try adding the following to your extra-deps in /home/beerend/Projects/intero-builder/new-template/stack.yaml:

- ghc-paths-0.1.0.9
- network-2.7.0.2
- random-1.1
- syb-0.7

Plan construction failed.
beerend@beerend-ThinkPad-X1-Carbon-5th:~/Projects/intero-builder/new-template$ nano stack.yaml
beerend@beerend-ThinkPad-X1-Carbon-5th:~/Projects/intero-builder/new-template$ stack build intero
random-1.1: configure
random-1.1: build
ghc-paths-0.1.0.9: configure
network-2.7.0.2: download
ghc-paths-0.1.0.9: build
syb-0.7: configure
ghc-paths-0.1.0.9: copy/register
syb-0.7: build
network-2.7.0.2: configure
random-1.1: copy/register                         
syb-0.7: copy/register                            
network-2.7.0.2: build                
network-2.7.0.2: copy/register
intero-0.1.32: configure     
intero-0.1.32: build       
intero-0.1.32: copy/register
Completed 5 action(s).     
beerend@beerend-ThinkPad-X1-Carbon-5th:~/Projects/intero-builder/new-template$ stack build intero --copy-compiler-tool 
Copying from /home/beerend/Projects/intero-builder/new-template/.stack-work/install/x86_64-linux/ghc-8.4.2/8.4.2/bin/intero to /home/beerend/.stack/compiler-tools/x86_64-linux/ghc-8.4.2/bin/intero

Copied executables to /home/beerend/.stack/compiler-tools/x86_64-linux/ghc-8.4.2/bin:
- intero
```

**Comment by effectfully** [comment]
@beerendlauwers, thank you very much, it helped.
